---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      cluster: "datagrid"
    name: datagrid-repo
  spec:
    replicas: 3
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 10
        intervalSeconds: 20
        timeoutSeconds: 600
        maxUnavailable: 1
        maxSurge: 1
    selector:
      cluster: "datagrid"
    template:
      metadata:
        labels:
          cluster: "datagrid"
      spec:
        containers:
        - args:
          - custom/server-config
          - -Djboss.default.jgroups.stack=kubernetes
          - --debug
          image: jboss/infinispan-server:9.0.3.Final
          imagePullPolicy: Always
          name: infinispan-server
          ports:
          - containerPort: 8888
            protocol: TCP
          - containerPort: 11222
            protocol: TCP
          env:
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: "cluster=datagrid"
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom: {fieldRef: {apiVersion: v1, fieldPath: metadata.namespace}}
          - name: JAVA_OPTS
            value: "-server -Xms128m -Xmx1024m -XX:+UseConcMarkSweepGC -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -XX:+PrintGC"
#          - name: APP_USER
#            value: "developer"
#          - name: APP_PASS
#            value: "developer"
          terminationMessagePath: /dev/termination-log
          terminationGracePeriodSeconds: 90
          volumeMounts:
          - mountPath: /opt/jboss/infinispan-server/standalone/configuration/custom
            name: config-volume
          - mountPath: /opt/jboss/infinispan-server/standalone/deployments
            name: app-jar-volume
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/is_running.sh
            initialDelaySeconds: 10
            timeoutSeconds: 80
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
             exec:
                command:
                - /usr/local/bin/is_healthy.sh
             initialDelaySeconds: 10
             timeoutSeconds: 40
             periodSeconds: 30
             successThreshold: 2
             failureThreshold: 5
        restartPolicy: Always
        volumes:
        - configMap:
            name: server-configuration
          name: config-volume
        - name: app-jar-volume
          hostPath:
            path: /Users/g/0/events/swiss-transport-datagrid/datagrid/target
#            path: /opt/deployments
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      cluster: "datagrid"
    name: "datagrid-repo-cache"
  spec:
    ports:
    - name: kube-ping
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: hotrod
      port: 11222
      protocol: TCP
      targetPort: 11222
    selector:
      cluster: "datagrid"
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: "datagrid-repo"
  spec:
    ports:
    - name: kube-ping
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: hotrod
      port: 11222
      protocol: TCP
      targetPort: 11222
    selector:
      cluster: "datagrid"
    type: LoadBalancer
#- apiVersion: v1
#  kind: Service
#  metadata:
#    creationTimestamp: null
#    labels:
#      group: org.infinispan.microservices
#      project: session-demo
#      provider: fabric8
#      version: 1.0.0-SNAPSHOT
#    name: session-demo
#  spec:
#    ports:
#    - port: 8080
#      protocol: TCP
#      targetPort: 8080
#    selector:
#      group: org.infinispan.microservices
#      project: session-demo
#      provider: fabric8
#    sessionAffinity: None
#    type: ClusterIP
#- apiVersion: v1
#  kind: Route
#  metadata:
#    labels:
#      group: org.infinispan.microservices
#      project: session-demo
#      provider: fabric8
#      version: 1.0.0-SNAPSHOT
#    name: session-demo
#  spec:
#    host: session-demo-myproject.192.168.0.17.nip.io
#    port:
#      targetPort: 8080
#    to:
#      kind: Service
#      name: session-demo
#      weight: 100
#    wildcardPolicy: None
#  status:
#    ingress:
#    - conditions:
#      - lastTransitionTime: 2017-03-07T08:10:22Z
#        status: "True"
#        type: Admitted
#      host: session-demo-myproject.192.168.0.17.nip.io
#      routerName: router
#      wildcardPolicy: None