---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      cluster: "datagrid"
    name: datagrid
  spec:
    replicas: 3
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 10
        intervalSeconds: 20
        timeoutSeconds: 600
        maxUnavailable: 1
        maxSurge: 1
    selector:
      cluster: "datagrid"
    template:
      metadata:
        labels:
          cluster: "datagrid"
      spec:
        containers:
        - args:
          - custom/server-config
          - -Djboss.default.jgroups.stack=kubernetes
          - --debug
          image: galderz/infinispan-server:9.0.x-1e092e9e993c
          imagePullPolicy: Always
          name: infinispan-server
          ports:
          - containerPort: 8888
            protocol: TCP
          - containerPort: 11222
            protocol: TCP
          env:
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: "cluster=datagrid"
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom: {fieldRef: {apiVersion: v1, fieldPath: metadata.namespace}}
          - name: JAVA_OPTS
            value: "-server -Xms128m -Xmx1024m -XX:+UseConcMarkSweepGC -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -XX:+PrintGC"
#          - name: APP_USER
#            value: "developer"
#          - name: APP_PASS
#            value: "developer"
          terminationMessagePath: /dev/termination-log
          terminationGracePeriodSeconds: 90
          volumeMounts:
          - mountPath: /opt/jboss/infinispan-server/standalone/configuration/custom
            name: config-volume
          - mountPath: /opt/jboss/infinispan-server/standalone/deployments
            name: app-jar-volume
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/is_running.sh
            initialDelaySeconds: 10
            timeoutSeconds: 80
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
             exec:
                command:
                - /usr/local/bin/is_healthy.sh
             initialDelaySeconds: 10
             timeoutSeconds: 40
             periodSeconds: 30
             successThreshold: 2
             failureThreshold: 5
        restartPolicy: Always
        volumes:
        - configMap:
            name: server-configuration
          name: config-volume
        - name: app-jar-volume
          hostPath:
            path: /Users/g/0/events/gids17/swiss-transport-datagrid/datagrid/target
#            path: /opt/deployments
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      cluster: "datagrid"
    name: "datagrid"
  spec:
    ports:
    - name: kube-ping
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: hotrod
      port: 11222
      protocol: TCP
      targetPort: 11222
    selector:
      cluster: "datagrid"
    type: ClusterIP
